workflows:
  android-workflow:
      name: Android Build
          max_build_duration: 60
              environment:
                    flutter: stable
                        scripts:
                              - name: Get Flutter packages
                                      script: |
                                                cd nohelia_app
                                                          flutter pub get
                                                                - name: Build APK
                                                                        script: |
                                                                                  cd nohelia_app
                                                                                            flutter build apk --release
                                                                                                artifacts:
                                                                                                      - nohelia_app/build/app/outputs/flutter-apk/app-release.apk