import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

void main() {
  runApp(NoheliaApp());
  }

  class NoheliaApp extends StatelessWidget {
    @override
      Widget build(BuildContext context) {
          return MaterialApp(
                debugShowCheckedModeBanner: false,
                      title: 'Nohelia',
                            theme: ThemeData(
                                    primarySwatch: Colors.indigo,
                                          ),
                                                home: NoheliaHome(),
                                                    );
                                                      }
                                                      }

                                                      class NoheliaHome extends StatefulWidget {
                                                        @override
                                                          _NoheliaHomeState createState() => _NoheliaHomeState();
                                                          }

                                                          class _NoheliaHomeState extends State<NoheliaHome> {
                                                            List<Map<String, String>> mensajes = [
                                                                {
                                                                      "autor": "nohelia",
                                                                            "texto": "Hola David… soy Nohelia. Estoy aquí para ti."
                                                                                }
                                                                                  ];

                                                                                    final TextEditingController _controller = TextEditingController();

                                                                                      // Función para conectarse a la IA gratuita
                                                                                        Future<String> generarRespuesta(String mensaje) async {
                                                                                            try {
                                                                                                  final url = Uri.parse(
                                                                                                            'https://api.affiliateplus.xyz/api/chatbot?message=${Uri.encodeComponent(mensaje)}&botname=Nohelia&ownername=David');

                                                                                                                  final response = await http.get(url);

                                                                                                                        if (response.statusCode == 200) {
                                                                                                                                final data = json.decode(response.body);
                                                                                                                                        return data['message'] ?? "Hmm… no entendí eso, David.";
                                                                                                                                              } else {
                                                                                                                                                      return "Ups… algo falló, David.";
                                                                                                                                                            }
                                                                                                                                                                } catch (e) {
                                                                                                                                                                      return "Error de conexión, David.";
                                                                                                                                                                          }
                                                                                                                                                                            }

                                                                                                                                                                              // Función para enviar el mensaje del usuario
                                                                                                                                                                                void enviarMensaje() async {
                                                                                                                                                                                    String mensajeUsuario = _controller.text;

                                                                                                                                                                                        if (mensajeUsuario.isEmpty) return;

                                                                                                                                                                                            setState(() {
                                                                                                                                                                                                  mensajes.add({"autor": "usuario", "texto": mensajeUsuario});
                                                                                                                                                                                                        _controller.clear();
                                                                                                                                                                                                            });

                                                                                                                                                                                                                String respuestaIA = await generarRespuesta(mensajeUsuario);

                                                                                                                                                                                                                    setState(() {
                                                                                                                                                                                                                          mensajes.add({"autor": "nohelia", "texto": respuestaIA});
                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                  @override
                                                                                                                                                                                                                                    Widget build(BuildContext context) {
                                                                                                                                                                                                                                        return Scaffold(
                                                                                                                                                                                                                                              backgroundColor: Colors.indigo.shade50,
                                                                                                                                                                                                                                                    appBar: AppBar(
                                                                                                                                                                                                                                                            title: Text("Nohelia"),
                                                                                                                                                                                                                                                                    centerTitle: true,
                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                body: Column(
                                                                                                                                                                                                                                                                                        children: [
                                                                                                                                                                                                                                                                                                  Expanded(
                                                                                                                                                                                                                                                                                                              child: ListView.builder(
                                                                                                                                                                                                                                                                                                                            padding: EdgeInsets.all(10),
                                                                                                                                                                                                                                                                                                                                          itemCount: mensajes.length,
                                                                                                                                                                                                                                                                                                                                                        itemBuilder: (context, index) {
                                                                                                                                                                                                                                                                                                                                                                        final mensaje = mensajes[index];
                                                                                                                                                                                                                                                                                                                                                                                        final esUsuario = mensaje["autor"] == "usuario";

                                                                                                                                                                                                                                                                                                                                                                                                        return Align(
                                                                                                                                                                                                                                                                                                                                                                                                                          alignment:
                                                                                                                                                                                                                                                                                                                                                                                                                                                esUsuario ? Alignment.centerRight : Alignment.centerLeft,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  child: Container(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      margin: EdgeInsets.symmetric(vertical: 5),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: EdgeInsets.all(12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              decoration: BoxDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: esUsuario
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? Colors.indigo.shade200
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: BorderRadius.circular(12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mensaje["texto"]!,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style: TextStyle(fontSize: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: EdgeInsets.all(10),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: Row(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Expanded(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  controller: _controller,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      decoration: InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            hintText: "Escríbeme algo, David…",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )